# async 和 await

- 重要,以后应该会大量使用!

async 和 await 是 ES2017/ES8 新增两个关键字，它们借鉴了 ES2015 中生成器在实际开发中的应用，目的是简化 Promise api 的使用，并非是替代 Promise。

**是一种语法糖,相当强大啊,但它并不能完全取代PromiseAPI,比如在setTimeout中return时,所以需要我们改造计时器函数**
```js
//因为setTimeout里的return,返回的不是我们想要返回的地方
//因为它只是setTimeout的回调函数里的返回而已
        //所以这里要改造计时器
        function delay(duration) {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve();
                }, duration);
            })
        }
        //必须等待到指定时间才能返回
        async function biaobai(god) {
            console.log(`邓哥向${god}发出了表白短信`);
            await delay(500);
            return Math.random() < 0.3;
        }
```


## async(异步)

目的是简化在函数的返回值中对Promise的创建

`async用于修饰函数(无论是函数字面量还是函数表达式),放置在函数最开始的位置,被修饰函数的返回结果一定是一个Promise对象`

```js

async function test(){
    console.log(1);
    //throw 3;//这样就是reject(3);
    //如果返回的是一个promise对象呢,那就会直接用这个返回的promise
    //但是没必要啊,我已经用了async还返回新promise干嘛呢
    //return new Promise(resolve => {
    //    resolve(5);
    //})
    return 2;//resolve(2);
}

//等效于

function test(){
    return new Promise((resolve, reject)=>{
        console.log(1);
        resolve(2);
    })
}

```

## await(等待)

**await关键字必须出现在async函数中！！！！**

`await用在某个表达式之前，如果表达式是一个Promise，则得到的是thenable中的状态数据。`

**`await之后的所有代码(不单指那一行)其实就是都放到了then里面的,都是异步的,你不完成我就一直等`**

```js

async function test1(){
    console.log(1);
    return 2;
}

async function test2(){
    const result = await test1();
    console.log(result);
}

test2();
```

等效于

```js

function test1(){
    return new Promise((resolve, reject)=>{
        console.log(1);
        resolve(2);
    })
}

function test2(){
    return new Promise((resolve, reject)=>{
        test1().then(data => {//等test1 fulfilled之后,再把data给result
            const result = data;//就是在这里把状态数据给result的
            console.log(result);//await后面的语句就从上条语句完成之后开始执行
            //但都是在异步里了,在then中呢
            resolve();//你们都干完了,然后我再resolve,因为上面那里没有return一个明确的值,所以参数不写,这个resolve必须写进这个then里面,因为要在异步结束后fulfilled
        });
    })
}

test2();

```

## 细节补充

1. `如果当前循环里，等待的Promise没有resolve，则不运行下一次循环`
2. 对于处理错误,加个try{}catch(e){}即可
```js
async function getPromise() {
            if (Math.random() < 0.5) {
                return 1;
            } else {
                throw 2;
            }
        }

async function test() {
    try {
        const result = await getPromise();
        console.log("正常状态", result)
    } catch (err) {
        console.log("错误状态", err);
    }
}

test();
```
3. **`如果await的表达式不是Promise`，则会`将其使用Promise.resolve包装后按照规则运行`**
