<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <script>
        const pro1 = new Promise((resolve, reject) => {
            throw 1;
        })
        const pro2 = pro1.then(result => {//pro2的状态只跟这里的then有关系
            return result * 2
        }, err => {//虽然pro1先来rejected了
            return err * 3;//1*3,但是err里面是正常处理的,所以pro2后来变成了resolve状态
        });


        pro1.catch(err => {//这相当于是const pro3 = ...
            return err * 2;
        })
        //pro2类型：Promise对象
        //pro2的状态：
        pro2.then(result => console.log(result * 2), err => console.log(err * 3))
        //3*2
        //输出：6
    </script>
</body>

</html>